Bugfix/sequence diagram update: Update API data retrieval diagrams
eclipse-tractusx/eco-pass-kit pull request #29
Opened 2023-12-20 16:58 UTC by matbmoser

# Why we create this PR?
 
The API diagrams are outdated and because of this they need to be modified
 
# What we want to achieve with this PR?
 
Update API diagrams based on the Digital Product Pass and also add the data retrieval guide flow
 
# What is new?
 
## Added
- Data Retrieval Flow diagram added
- Added description on how to retrieve data

## Updated
- Updated diagram with API to search for digital twin registries

2024-01-04 17:16 UTC, maxim-bo requested changes
Overall fine, however, some open questions remain and should be looked at (see comments)

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +In order to achieve a better understanding of the Eco Pass KIT data retrieval flow, we can detail a specific example where an user wants to retrieve an specific passport for a asset in Catena-X using
"Eco Pass" -> "EcoPass"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +| `<manufacturerPartId>` | The "**manufacturerPartId**" makes reference to the id type of the product. Is the identification the manufacturer gives to an specific part he produced.
"Is" -> "It is"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +| EDC                   | Main gateaway to the network. In this use case two edc need be existing, one connected to the Digital Product Pass (Eco Pass KIT) [EDC Consumer] and another to the Provider
"In this use case two edc need be existing" -> "EDC" (capital letters)
"Eco Pass" -> "EcoPass"
"Provider Catena-X components" -> "Provider **of** Catena-X components" ?

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +| Digital Product Pass  | The [**Eco Pass KIT**] reference implementation. The application responsible for retrieving the passports and interacting with the services listed above.
"EcoPass"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +At the beginning we start calling the `Discovery Service` which is responsible for giving us the urls from the `BPN Discovery` and the `EDC Discovery` this two service give us first a `BPN or Busines
A dot after "EDC Discovery", starting a new sentence afterwards would improve readability

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +Once we have the submodel we are going to call the [`subprotocolBody`](#L233) url of the `endpoint interface` with name `SUBMODEL-3.0`. This will provide for us the asset id to negotiate with the EDC
The "And" in "And in this way ..." in the last sentence can be omitted, i guess :)

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +After the discovery phase, the search for digital twin registries is one of the core phases to be done when retrieving data in Catena-X. Is necessary for filtering the EDCs which contain the digital
"**It** is necessary"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +> **NOTE**: For learning how to register the assets and the digital twin registry and operate the Eco Pass KIT visit the [Operation View](./page-software-operation-view.md)
"EcoPass"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +The Eco Pass KIT has two authorization methods:
"EcoPass"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +> **NOTE**: The authorization can be configure in the Eco Pass KIT configuration so that it matches the business interests of the Operator.
configure**d**

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +The Digital Product Pass / Eco Pass KIT Open API specification is available at the swagger hub from Tractus-X:
EcoPass

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +### Eco Pass APIs
EcoPass

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> + | **/api/contract/search**              | POST   | At the **/api/contract/search**  API the user can search for a serialized Id and get its contract. The `Backend` will search for the Digital Twin a
"A `sign token` (a sha256 hash) is return**ed** also"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> + | **/api/contract/cancel**              | POST   | The user can use `/cancel` to interrupt the negotiation process once it is signed by mistake if is the case. It will be only valid until the negoti
"signed by mistake if **this/it** is the case"

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
>  - SPDX-FileCopyrightText: 2023,2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
licensing footer needs update to "2023, 2024"

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/dataRetrievalFlow.jpg
is it possible to refer to the concrete steps (1, 2, 3, .., 10) in the corresponding chapters in the software development view document? -> "At the beginning we start calling the `Discovery Service` **(step 1)** which is responsible for giving us the urls from the `BPN Discovery` **(step 2)** and the `EDC Discovery` **(step 3)** [...]"

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/dataRetrievalFlow.jpg
Its just an idea, however, i do like references between figures and the corresponding text passages :)

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/dataRetrievalFlow.jpg.license
> +- SPDX-FileCopyrightText: 2023,2023 ZF Friedrichshafen AG
Update to 2023, 2024 as discussed

2024-01-04 17:16 UTC, maxim-bo commented on docs/page-software-development-view.md
> +Here is a diagram of the data retrial flow necessary to retrieve any data from the Catena-X Network without any optimizations:
"retri**v**al"

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/developmentview-sequence-diagramm.svg
Is this really a "Digital Twin Registry Discovery Architecture" (header of figure) or rather a "sequence diagram", "process flow", or "data retrieval flow" (as called in the text)

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/developmentview-sequence-diagramm.svg.license
>  - SPDX-FileCopyrightText: 2023,2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
update to 2023, 2024

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/ecoPassNegotiationAndTransferSequence.svg
Title requires an "**s**" in Tran**s**fer

Is it correct that the objects are called "EcoPass **KIT** FRONTEND" and "EcoPass **KIT** BACKEND", respectively? Is it really the **KIT** Front- or Backend that acts here?

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/ecoPassNegotiationAndTransferSequence.svg.license
> +- SPDX-FileCopyrightText: 2023,2023 ZF Friedrichshafen AG
Update to 2023, 2024

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/ecoPassSearchSequence.svg
Again, please check whether this really is an architecture or rather a sequence/flow/process diagram + EcoPass **KIT** Frontend/Backend -> Is it really the Front-/Backend of the KIT?

2024-01-04 17:16 UTC, maxim-bo commented on docs/resources/development-view/ecoPassSearchSequence.svg.license
> +- SPDX-FileCopyrightText: 2023,2023 ZF Friedrichshafen AG
Update to 2023, 2024

2024-01-09 07:32 UTC, matbmoser commented on docs/page-software-development-view.md
> +In order to achieve a better understanding of the Eco Pass KIT data retrieval flow, we can detail a specific example where an user wants to retrieve an specific passport for a asset in Catena-X using
ok

2024-01-09 07:34 UTC, matbmoser commented on docs/page-software-development-view.md
> +| EDC                   | Main gateaway to the network. In this use case two edc need be existing, one connected to the Digital Product Pass (Eco Pass KIT) [EDC Consumer] and another to the Provider
I think it needs to be Catena-X Provider Components. I also added the "s" in the EDC so that it becomes plural

2024-01-09 07:34 UTC, matbmoser commented on docs/page-software-development-view.md
> +| Digital Product Pass  | The [**Eco Pass KIT**] reference implementation. The application responsible for retrieving the passports and interacting with the services listed above.
Done!

2024-01-09 07:36 UTC, matbmoser commented on docs/page-software-development-view.md
> +Here is a diagram of the data retrial flow necessary to retrieve any data from the Catena-X Network without any optimizations:
Retrieval actually but good that you spotted that ! :)

2024-01-09 07:37 UTC, matbmoser commented on docs/page-software-development-view.md
> +At the beginning we start calling the `Discovery Service` which is responsible for giving us the urls from the `BPN Discovery` and the `EDC Discovery` this two service give us first a `BPN or Busines
You are right. Its better to read then...

2024-01-09 07:37 UTC, matbmoser commented on docs/page-software-development-view.md
> +Once we have the submodel we are going to call the [`subprotocolBody`](#L233) url of the `endpoint interface` with name `SUBMODEL-3.0`. This will provide for us the asset id to negotiate with the EDC
Ok

2024-01-09 07:37 UTC, matbmoser commented on docs/page-software-development-view.md
> +After the discovery phase, the search for digital twin registries is one of the core phases to be done when retrieving data in Catena-X. Is necessary for filtering the EDCs which contain the digital
nice spotted!

2024-01-09 07:38 UTC, matbmoser commented on docs/page-software-development-view.md
> +> **NOTE**: The authorization can be configure in the Eco Pass KIT configuration so that it matches the business interests of the Operator.
done!

2024-01-09 07:38 UTC, matbmoser commented on docs/page-software-development-view.md
> +The Digital Product Pass / Eco Pass KIT Open API specification is available at the swagger hub from Tractus-X:
Ok

2024-01-09 07:38 UTC, matbmoser commented on docs/page-software-development-view.md
> + | **/api/contract/search**              | POST   | At the **/api/contract/search**  API the user can search for a serialized Id and get its contract. The `Backend` will search for the Digital Twin a
nice!

2024-01-09 07:39 UTC, matbmoser commented on docs/page-software-development-view.md
> + | **/api/contract/cancel**              | POST   | The user can use `/cancel` to interrupt the negotiation process once it is signed by mistake if is the case. It will be only valid until the negoti
true

2024-01-09 07:44 UTC, matbmoser commented on docs/resources/development-view/dataRetrievalFlow.jpg.license
> +- SPDX-FileCopyrightText: 2023,2023 ZF Friedrichshafen AG
thats updated in the latest version

2024-01-09 07:45 UTC, matbmoser commented on docs/page-software-development-view.md
>  - SPDX-FileCopyrightText: 2023,2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
Thats updated in the latest version

2024-01-09 07:45 UTC, matbmoser commented on docs/resources/development-view/developmentview-sequence-diagramm.svg.license
>  - SPDX-FileCopyrightText: 2023,2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
thats also updated

2024-01-09 07:45 UTC, matbmoser commented on docs/resources/development-view/ecoPassNegotiationAndTransferSequence.svg.license
> +- SPDX-FileCopyrightText: 2023,2023 ZF Friedrichshafen AG
this also

2024-01-09 07:45 UTC, matbmoser commented on docs/resources/development-view/ecoPassSearchSequence.svg.license
> +- SPDX-FileCopyrightText: 2023,2023 ZF Friedrichshafen AG
this also

2024-01-09 07:46 UTC, matbmoser commented on docs/resources/development-view/ecoPassNegotiationAndTransferSequence.svg
ok, I will check how can I make it better

2024-01-09 08:25 UTC, matbmoser commented on docs/resources/development-view/ecoPassSearchSequence.svg
Yes backend and frontend and different components of the Digital Product Pass, now when it comes to the kit maybe we can think something else...

2024-01-12 10:46 UTC, merged